# Declarative GitHub labels for this repo
# Managed by GitHub Actions workflow: .github/workflows/labels.yml

# --- Phase ---
- name: 'phase:P0-setup'
  color: 'C5DEF5'
  description: 'Supabase init, env, base setup'
- name: 'phase:P1-mvp'
  color: 'C5DEF5'
  description: 'Auth + workspace + projects/tasks + realtime'
- name: 'phase:P2-microservices'
  color: 'C5DEF5'
  description: 'Split services + gateway + Kafka events'
- name: 'phase:P3-async'
  color: 'C5DEF5'
  description: 'RabbitMQ workers + retry/DLQ'
- name: 'phase:P4-mobile'
  color: 'C5DEF5'
  description: 'React Native + offline sync/outbox'
- name: 'phase:P5-production'
  color: 'C5DEF5'
  description: 'Docker + CI/CD + monitoring + perf'

# --- Type ---
- name: 'type:feature'
  color: 'A2EEEF'
  description: 'New feature'
- name: 'type:bug'
  color: 'D73A4A'
  description: 'Bug fix'
- name: 'type:chore'
  color: 'F9D0C4'
  description: 'Maintenance / tooling'
- name: 'type:docs'
  color: '0075CA'
  description: 'Documentation'
- name: 'type:refactor'
  color: 'C2E0C6'
  description: 'Refactor without behavior change'
- name: 'type:test'
  color: 'BFDADC'
  description: 'Tests'

# --- Area ---
- name: 'area:web'
  color: '7057FF'
  description: 'Next.js web'
- name: 'area:mobile'
  color: '7057FF'
  description: 'React Native app'
- name: 'area:api'
  color: '7057FF'
  description: 'Gateway/API'
- name: 'area:db'
  color: '7057FF'
  description: 'Database, RLS, migrations'
- name: 'area:realtime'
  color: '7057FF'
  description: 'Realtime subscriptions'
- name: 'area:kafka'
  color: '7057FF'
  description: 'Kafka topics/consumers/producers'
- name: 'area:rabbitmq'
  color: '7057FF'
  description: 'Queues/workers/retry/DLQ'
- name: 'area:auth'
  color: '7057FF'
  description: 'Supabase auth + RBAC'
- name: 'area:infra'
  color: '7057FF'
  description: 'Docker/compose/hosting'
- name: 'area:observability'
  color: '7057FF'
  description: 'Logs/metrics/tracing'
- name: 'area:perf'
  color: '7057FF'
  description: 'Load test + optimization'

# --- Priority ---
- name: 'prio:P0'
  color: 'B60205'
  description: 'Must do now'
- name: 'prio:P1'
  color: 'D93F0B'
  description: 'High'
- name: 'prio:P2'
  color: 'FBCA04'
  description: 'Medium'
- name: 'prio:P3'
  color: '0E8A16'
  description: 'Low'

# --- Status (optional) ---
- name: 'status:blocked'
  color: '000000'
  description: 'Blocked by dependency'
- name: 'status:needs-review'
  color: '5319E7'
  description: 'Needs review'
- name: 'status:ready'
  color: '1D76DB'
  description: 'Ready to pick up'
